" ******************************************************************************
" file: gvimrc
" desc: gvim configuratie
" date: 2016-04
" auth: dpa
" ******************************************************************************

" windows grootte en positie
set winpos 14 50
set lines=55
set columns=160

" eof
"
